/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge.vue')['default']
    BarChart: typeof import('./src/components/Charts/BarChart.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    Card: typeof import('./src/components/ui/card.vue')['default']
    CardContent: typeof import('./src/components/ui/card-content.vue')['default']
    CardHeader: typeof import('./src/components/ui/card-header.vue')['default']
    CardTitle: typeof import('./src/components/ui/card-title.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DashboardFilters: typeof import('./src/components/DashboardFilters.vue')['default']
    DashboardTable: typeof import('./src/components/DashboardTable.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    FeatherIcon: typeof import('./src/components/FeatherIcon.vue')['default']
    Input: typeof import('./src/components/ui/input.vue')['default']
    Label: typeof import('./src/components/ui/label.vue')['default']
    PeriodSelector: typeof import('./src/components/PeriodSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    Select: typeof import('./src/components/ui/select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select-content.vue')['default']
    SelectItem: typeof import('./src/components/ui/select-item.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select-trigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select-value.vue')['default']
    Table: typeof import('./src/components/ui/table.vue')['default']
    TableBody: typeof import('./src/components/ui/table-body.vue')['default']
    TableCell: typeof import('./src/components/ui/table-cell.vue')['default']
    TableHead: typeof import('./src/components/ui/table-head.vue')['default']
    TableHeader: typeof import('./src/components/ui/table-header.vue')['default']
    TableRow: typeof import('./src/components/ui/table-row.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
